name: GitHub Actions - Firebase Deployment
on:
  push: 
    branches: ['master']

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  deploy-hugo-firebase:
    name: Deploy
    runs-on: nwbyio/hugo-firebase
    steps:
      - run: hugo
      - run: echo $PROJECT_ID
      - run: echo $FIREBASE_TOKEN
      - run: firebase deploy --token $FIREBASE_TOKEN --project $PROJECT_ID --only hosting
    
